import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "../../Components/Header";
import Footer from "../../Components/Footer";
import Container from "../../Components/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "League-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={inter.className} lang="en">
      <body>
        <Header />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
